### ISSUE TITLE
the obvious one: Where's the Beef- er, Build?

### ISSUE THREAD

**Issue by sirocyl** [sirocyl/MaxiTracker#1]
There is no existing build of MaxiTracker. The process to build it is identical to j0CC-FamiTracker, so it shouldn't be hard to do. I just don't have a dev machine running Windows at this time.

If someone trusted provides a build I will include it at the Releases tab.

**Comment by simontime** [comment]
Built it for ya: [MaxiTracker.zip](https://github.com/sirocyl/MaxiTracker/files/3440625/MaxiTracker.zip)

**Comment by sirocyl** [comment]
Added build to README, closing.

**Comment by OPNA2608** [comment]
You can set up CI automation to automatically test the code & upload a build. Take a look here:
https://github.com/marysiamzawka/j0CC-FamiTracker/blob/master/.github/workflows/ccpp.yml
https://github.com/marysiamzawka/j0CC-FamiTracker/actions/runs/83659776

For downloads that don't expire, you'd have to setup uploads to the releases page.
